project_name: tome
builds:
  - main: ./cmd/tome/main.go
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    replacements:
      drawin: macOS
      windows: Windows
      linux: Linux
    files:
      - LICENSE
      - REAEDME.md
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: kpiljoong
    name: tome
  draft: true
  prerelease: auto

checksum:
  name_template: "checksums.txt"
