version: 1
project_name: tome

builds:
  - main: ./cmd/tome/main.go
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{.Version}}
    binary: tome

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: kpiljoong
    name: tome
  draft: false
  prerelease: auto

checksum:
  name_template: "checksums.txt"
